source "http://rubygems.org"

require 'rbconfig'

gem 'rails', '>= 4.2.1'

#gem 'debugger'

# assets
gem 'sass', '>= 3.4.13'
gem 'compass', '>= 1.0.3'
gem 'scss-lint', '>= 0.35.0'

# doc
gem 'jsduck', '>= 5.3.4'
gem 'jekyll', '>= 2.5.3'
gem 'jekyll-paginate'
gem 'jekyll-sitemap'
gem 'hologram', '>= 1.4.0'

# other
gem 'pygments.rb', '~> 0.6.3'
gem 'rdiscount', '>= 2.1.8'
gem 'windows-pr', '~> 1.2.4'
gem 'win32console', '~> 1.3.2'

group :jekyll_plugins do
  gem 'octopress-paginate'
end